baseURL = "https://pixboost.com/"
languageCode = "en-us"
title = "Pixboost Image CDN"
theme = "pixboost"
enableRobotsTXT = true
enableGitInfo = true
disableKinds = ['taxonomy', 'term']

[frontmatter]
    lastmod = ['lastmod', ':git', 'date', 'publishDate']


